export const Users = {
  brian: "bdr.visuals",
  noah: "826.media",
  bensCarPics: "benscarpics",
  dallasInBlack: "dallasinblack",
  munstrography: "munstrography",
  arzolasVisuals: "arzolas_visuals",
  stellerVisuals: "stellervisuals",
  snapperSociety: "snappersociety",
  splitMedia: "split_media_",
  srikar: "shotbysrikar",
  mayitoShoots: "mayitoshoots",
  snowzilla: "snowzilla",
  rakkzo: "rakkzo",
  lundPhotos: "lund.photos",
  brmPhotos: "brm.photos",
};
